/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import ticket.booking.entities.Train;
import ticket.booking.entities.User;
import ticket.booking.services.UserBookingServices;
import ticket.booking.util.UserServiceUtil;

import java.io.IOException;
import java.util.*;

public class App {

    public static void main(String[] args){
        System.out.println("Running Train Booking Service");
        Train trainSelectedForBooking = new Train();
        UserBookingServices userBookingServices;
        try {
            userBookingServices = new UserBookingServices();
        } catch (IOException e) {
            System.out.println("Error: " + e.getMessage());
            throw new RuntimeException(e);

        }
        Scanner sc = new Scanner(System.in);
        int choice = 0;
        System.out.println("Please Choose from  the following options:");
        System.out.println("1. Sign Up");
        System.out.println("2. Log In");
        System.out.println("3. Fetch Booking");
        System.out.println("4. Search For  Trains");
        System.out.println("5. Book a Ticket");
        System.out.println("6. Cancel Booking");
        System.out.println("7. Exit");
        choice = sc.nextInt();
        switch (choice) {
            case 1:
                System.out.println("Sign Up......");
                System.out.println("Please Enter Username");
                String signUpUserName = sc.next();
                System.out.println("Please Enter Password");
                String signUpPassword = sc.next();
                User userForSignup = new User(signUpUserName,signUpPassword, UserServiceUtil.hashpassword(signUpPassword),new ArrayList<>(), UUID.randomUUID().toString());
                userBookingServices.signUp(userForSignup);
                break;
                case 2:
                    System.out.println("Log In......");
                    System.out.println("Please Enter Username");
                    String loginUserName = sc.next();
                    System.out.println("Please Enter Password");
                    String loginPassword = sc.next();
                    User userForLogin = new User(loginUserName,loginPassword, UserServiceUtil.hashpassword(loginPassword),new ArrayList<>(), UUID.randomUUID().toString());
                    try {
                        userBookingServices = new UserBookingServices(userForLogin);

                    }catch (IOException ex){
                        System.out.println("Something Went Wrong");;
                    }
                    break;
                    case 3:
                        System.out.println("Fetch Booking.......");
                        userBookingServices.fetchBooking();
                        break;
                    case 4:
                        System.out.println("Search For Trains.......");
                        System.out.println("Please Enter Your Source Station");
                        String sourceStation = sc.next();
                        System.out.println("Please Enter Your Destination Station");
                        String destinationStation = sc.next();
                        List<Train> trains= userBookingServices.getTrains(sourceStation,sourceStation);
                        int index = 1;
                        for (Train t: trains){
                            System.out.println(index+" Train id : "+t.getTrainId());
                            for (Map.Entry<String, String> entry: t.getStationsTimes().entrySet()){
                                System.out.println("station "+entry.getKey()+" time: "+entry.getValue());
                            }
                        }
                        System.out.println("Select a train by typing 1,2,3...");
                        trainSelectedForBooking = trains.get(sc.nextInt());
                        break;
                        case 5:
                            System.out.println("Book Your Ticket......");
                            List<List<Integer>> setas = userBookingServices.fetchSeats(trainSelectedForBooking);




        }

    }
}
